#!/usr/bin/env ansible-playbook
---
- name: Installing Business Central
  hosts: localhost
  connection: local
  vars:
     openshift_master: https://openshift.example.com:8443
     openshift_domain: example.com
     openshift_domain_cloudapps: cloudapps.{{ openshift_domain }} 
     username: demo
     password: r3dh4t1!
     businesscentral_namespace: business-central
     businesscentral_docker_image: openshift/business-central:latest
     jboss_installers:
         - { name: "JBoss EAP 6.0 Installer", filename: "jboss-eap-6.4.0-installer.jar", url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=37383" }
         - { name: "JBoss EAP 6.4 Patch 7", filename: "jboss-eap-6.4.7-patch.zip", url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=43071" }
         - { name: "JBoss BRMS 6.3.0 GA Installer", filename: "jboss-brms-6.3.0.GA-installer.jar", url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=43631" }
  tasks:
#### Checking if the Installers are correct positioned
     - name: JBoss Installers are needed for this playbook   
       debug: msg="Be sure the {{ item.name }} file{{ ':' }} templates/rhcs-bc/installs/{{ item.filename}} exists ? Available at {{ item.url }}"
       with_items: "{{ jboss_installers }}"
     
     - name: Checking if JBoss Installers are avaible at templates/rhcs-bc/installs
       stat: path=templates/rhcs-bc/installs/{{ item.filename }}
       with_items: "{{ jboss_installers }}"
       register: jboss_installer_file
       failed_when: jboss_installer_file.stat.exists == False
       tags:  
          - check

     - name: Modifying all the installers so they have Running permissions
       file: path=templates/rhcs-bc/installs/{{ item.filename }} mode="u+x"
       with_items: "{{ jboss_installers }}"
       tags: 
          - check

#### Getting Registry's Information and Docker build the image 
     - name: Make sure this is OpenShift's Administrator
       command: oc login --username=system:admin --insecure-skip-tls-verify --server={{ openshift_master }}
          - registry

     - name: Get Docker Registry's IP
       command: oc get service/docker-registry --output jsonpath="{.spec.clusterIP}" --namespace default
       register: docker_registry_ip
       tags: 
          - registry

     - name: Get Docker Registry's Port
       command: oc get service/docker-registry --output jsonpath="{.spec.ports.*.port}" --namespace default
       register: docker_registry_port
       tags: 
          - registry

     - name: Set Docker Registry's Address
       set_fact: docker_registry={{ docker_registry_ip.stdout }}:{{ docker_registry_port.stdout }}
       tags: 
          - registry

     - name: Setting Docker's TAG{{ ':' }} {{ docker_registry }}/{{ businesscentral_docker_image }}
       set_fact: docker_tag={{ docker_registry }}/{{ businesscentral_docker_image }}
       tags:
          - registry

     - name: Prepare a Dockerfile which contains all the necessary information for Business Center
       template: src=templates/Dockerfile.j2 dest=templates/rhcs-bc/Dockerfile
       tags:
          - registry

     - name: Build the current image{{ ':' }} "docker build --no-cache --rm=true --force-rm --tag {{ docker_tag }} templates/rhcs-bc/" 
       command: docker build --no-cache --rm=true --force-rm --tag {{ docker_tag }} templates/rhcs-bc/
       tags: 
          - registry

#### Creating the Project/Namespace 
     - name: Delete any previously projects already created
       command: oc delete project {{ businesscentral_namespace }} 
       ignore_errors: True
       tags: 
          - project_creation

     - name: Create a new project name {{ businesscentral_namespace }} for a user {{ username }}
       command: oadm new-project {{ businesscentral_namespace }} --display-name="Business Central{{ ':' }} LATAM Red Hat Forum 2016" --admin={{ username }}
       register: project_creation
       until: project_creation.rc == 0
       retries: 5
       delay: 15
       tags:
          - project_creation

     - name: Adjust the Policies so Business Central doesn't have problems running on top of OpenShift
       command: oadm policy add-scc-to-user anyuid --namespace {{ businesscentral_namespace }} --serviceaccount=default
       tags:
          - project_creation

     - name: Create a ImageStream based on JBoss Demo Central{{ ':' }} jbossdemocentral/developer
       command: oc new-build "jbossdemocentral/developer" --name=business-central --binary=true --namespace {{ businesscentral_namespace }}
       tags: 
          - project_creation

     - name: Import the newly Docker Image created to a ImageStream in the current Project
       command: oc import-image --confirm=true --insecure=true developer --namespace {{ businesscentral_namespace }}
       register: image_import
       until: image_import.rc == 0
       retries: 5
       delay: 15
       tags:
          - project_creation

     - name: Start building based on a current directory
       command: oc start-build business-central --from-dir=templates/rhcs-bc/ --follow=true --wait=true --namespace {{ businesscentral_namespace }}
       tags:
          - project_creation

     - name: Create a new application based on this ImageStream{{ ':' }} business-central
       command: oc new-app business-central --namespace {{ businesscentral_namespace }}
       tags:
          - project_creation

     - name: Expose the route as business-central.{{ openshift_domain_cloudapps }} 
       command: oc expose service business-central --hostname=business-central.{{ openshift_domain_cloudapps }} --namespace {{ businesscentral_namespace }}
       tags:
          - project_creation
