#!/usr/bin/env ansible-playbook
---
- name: Checking if necessary files exist
  hosts: localhost
  connection: local
  vars:
     jboss_installers:
         - { name: "JBoss EAP 6.0 Installer", filename: "jboss-eap-6.4.0-installer.jar", url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=37383" }
         - { name: "JBoss EAP 6.4 Patch 7", filename: "jboss-eap-6.4.7-patch.zip", url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=43071" }
         - { name: "JBoss BRMS 6.3.0 GA Installer", filename: "jboss-brms-6.3.0.GA-installer.jar", url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=43631" }
  tasks:
     - debug: msg="Be sure the {{ item.name }} file{{ ':' }} templates/rhcs-bc/installs/{{ item.filename}} exists ? Available at {{ item.url }}"
       with_items: "{{ jboss_installers }}"

     - name: Checking if JBoss Installers are avaible at templates/rhcs-bc/installs
       stat: path=templates/rhcs-bc/installs/{{ item.filename }}
       with_items: "{{ jboss_installers }}"
       register: jboss_installer_file
       failed_when: jboss_installer_file.stat.exists == False

#     - name: One of the required files are missing. Unable to proceed. 
#       fail: msg="Make sure this file exists{{ ':' }} {{ item.name }} at templates/rhcs-bc/installs/{{ item.filename }} available on {{ item.url }}"
#       with_items: "{{ jboss_installers }}"
#       when: jboss_installer_file.stat.exists == False 
